version: "3.7"

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: PostgresSecret123!
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data